# Use root/example as user/password credentials
services:

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Taipei
    # (this is just an example, not intended to be a production configuration)
